### PR TITLE
Allow template rendering from the command line

### PR DESCRIPTION
**Pull request by maxlaverse**
Hey!
Would it be acceptable to have a feature to only render templates and not applying them ? Similar to what can be done with Helm ?

This allows parsing the generated template to extract some information for other tools, like all the images involved.

### CODE REVIEW

**Comment by KnVerey** [comment]
Hi! I think this is a great idea, and it fits in nicely with some thoughts I was having about the future of rendering in this tool (https://github.com/Shopify/kubernetes-deploy/issues/44#issuecomment-352906890). Can you make it a completely separate command though? Maybe `kubernetes-render`?  That would also require extracting a renderer class that could be called from both the new executable and `DeployTask`, which I think makes a lot of sense, especially as the renderer gets more complex. IMO the class extraction is also required for https://github.com/Shopify/kubernetes-deploy/pull/207, so please coordinate with @skaes (who isn't at Shopify either--it's great to have all these contributions! ❤️ ) about who will have time to do that piece first.

**Comment by maxlaverse** [comment]
Sure @KnVerey , I'll talk to him

**Comment by maxlaverse** [comment]
Hi @KnVerey.
I rebased the PR and introduced a new command as suggest.
Could you point me in the direction you want this feature to go ?

**Comment by maxlaverse** [comment]
I won't really have time to work on this pull-request anymore.
I prefer to close it and re-open it in the future if want to invest in that direction again.

**Pull request closed without merging**
