### PR TITLE
Adjust activesupport dependency to limit upper version to <6.0.0

### PR DESCRIPTION
**Pull request by basert**
This pull request tries to solve issue https://github.com/Shopify/kubernetes-deploy/issues/534

### CODE REVIEW

**Comment by dturn** [comment]
@basert Do you actually need ruby 2.3? (All support for Ruby 2.3 ended in March https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/). If not I'm thinking bumping our min ruby version 2.4 might be a bette approach here.

**Comment by basert** [comment]
Unfortunately company requires the use of Debian stretch and no backports. https://packages.debian.org/stretch/ruby seems to only include 2.3.3

**Comment by dturn** [comment]
I'm actually against capping the active support version to support an EoL version of Ruby. I'll leave it up to the other maintainers to voice an opinion on when we're going to drop support for ruby 2.3. For now can we use something like: 

```
if RUBY_VERSION >= '2.4'
  spec.add_dependency("activesupport", "~> 5.0")
else
  spec.add_dependency("activesupport", ">= 5.0")
end
```

**Comment by KnVerey** [comment]
> I'll leave it up to the other maintainers to voice an opinion on when we're going to drop support for ruby 2.3. 

How about we do as you suggest (conditional) right now and drop 2.3 with the move to `krane`?

**Comment by dturn** [comment]
As part of the 1.0 release we are officially not supporting ruby 2.3

**Pull request closed without merging**
