### PR TITLE
Find `.yaml` with discover_resources

### PR DESCRIPTION
**Pull request by wfarr**
Ran into this where `resource.yaml` wasn't discovered and since it's a valid extension for YAML files, seems worth supporting.

### CODE REVIEW

**Comment by ibawt** [comment]
I would love this!

**Comment by ibawt** [comment]
I rebased and added yaml.erb as well changed some fixtures for the test.

**Comment by kirs** [comment]
LGTM but the latest CI run look red.

**Comment by ibawt** [comment]
yah I'm debugging it when I get cycles.

**Comment by ibawt** [comment]
```
➜  @OTT-Ian-Quick kubernetes-deploy git:(support-dot-yaml-resources) ✗ rake test
Run options: --seed 15907

# Running:

........................................................................................

Finished in 277.978146s, 0.3166 runs/s, 1.3742 assertions/s.

88 runs, 382 assertions, 0 failures, 0 errors, 0 skips
➜  @OTT-Ian-Quick kubernetes-deploy git:(support-dot-yaml-resources) ✗
```

**Pull request merged**
