### PR TITLE
increase timeout to 15mins

### PR DESCRIPTION
**Pull request by katdrobnjakovic**
Fixes https://github.com/Shopify/redis-memcached/issues/195 

cc @shopify/redis-memcached @kwestein

### CODE REVIEW

**Comment by KnVerey** [comment]
Looking at the linked issue, is this high timeout something you want generically for all Redis resources, or is it a small minority that are expected to take this long? I ask because in https://github.com/Shopify/kubernetes-deploy/issues/225 we were discussing the possibility of adding a generic feature that would enable you to override the timeout on any individual resource via an annotation.

**Comment by katdrobnjakovic** [comment]
> Looking at the linked issue, is this high timeout something you want generically for all Redis resources, or is it a small minority that are expected to take this long?

Thanks for reading the linked PR 👍 We have only seen this timeout happen with the iq_* app redis resources; however, we are okay with this being global for all redis resources for now to solve the issues they are seeing. 

> I ask because in #225 we were discussing the possibility of adding a generic feature that would enable you to override the timeout on any individual resource via an annotation.

What is the timeframe for #225 to be shipped? We would definitely change to only overriding an individual resource using the annotation when that PR has shipped 👍

**Comment by KnVerey** [comment]
Nobody had started it, but I expect it to be quite easy to implement, so I'll whip up a PR now.

**Comment by KnVerey** [comment]
Opened that PR here: https://github.com/Shopify/kubernetes-deploy/pull/232. PTAL. As mentioned there, a third option is to make the `Redis` class use `progressDeadlineSeconds` if available, and set that to a really high value for the problematic resource.

**Comment by katdrobnjakovic** [comment]
Okay, Ill take a look. At first glance https://github.com/Shopify/kubernetes-deploy/pull/232 is addressing our problem in a better way (individual resource increase of the timeout rather than global) so I will close this PR and focus on reviewing https://github.com/Shopify/kubernetes-deploy/pull/232.

**Pull request closed without merging**
