### PR TITLE
Allow for multiple `--bindings` arguments.

### PR DESCRIPTION
**Pull request by kvs**
We developed a need to pass in multiple files with bindings in it. This allows for that usecase.

### CODE REVIEW

**Comment by dturn** [comment]
Simple enough, can you please add a test

**Comment by kvs** [comment]
Hmm, I don't think there are any tests that currently run `exe/kubernetes-deploy`. I'll see if I can find time to figure out how to best test that part of the code, or if we'll find a workaround :)

**Comment by dturn** [comment]
I think for now adding something to `test/unit/kubernetes-deploy/bindings_parser_test.rb ` would be good enough. Testing the exe's is on the roadmap, but requires a refactor.

**Comment by kvs** [comment]
There's nothing to test in that file, since BindingsParser never gets to see the multiple bindings - it all happens in the exe.

**Comment by kvs** [comment]
Cool, thanks @KnVerey

**Pull request merged**
