### PR TITLE
Enable Kubernetes 1.10 Tests

### PR DESCRIPTION
**Pull request by stefanmb**
**What**
Enable k8s 1.10 tests.

### CODE REVIEW

**Comment by stefanmb** [comment]
Getting 3 failures under 1.10:

> test_bad_container_on_stateful_sets_fails_with_rolling_update

> test_deploy_result_logging_for_mixed_result_deploy

> test_resource_watcher_reports_failed_after_timeout

All 3 are known flaky from https://docs.google.com/spreadsheets/d/16NeL3Q76n1IrRMmHwSJN6UjIKRDM4eABFN2keTjgYTw/

**Comment by dturn** [comment]
`test_failure_logs_from_unmanaged_pod_appear_in_summary_section` is failing in 1.10 as well as 1.9. Related to https://github.com/Shopify/kubernetes-deploy/pull/297

**Comment by dturn** [comment]
Any idea why CI on 1.10 is 3x slower than the other versions?

**Comment by stefanmb** [comment]
Probably the timeouts on test failures:

> 605.339419s test_deploy_result_logging_for_mixed_result_deploy#KubernetesDeployTest

**Comment by dturn** [comment]
@stefanmb Can you rebase, I just merged a change that should fix ci

**Comment by stefanmb** [comment]
I can have a look at it later in the week, thanks for confirming the failures.

**Comment by stefanmb** [comment]
Closing in favour of https://github.com/Shopify/kubernetes-deploy/pull/308.

**Pull request closed without merging**
