### PR TITLE
Support label based namespace partitioning

### LINKED ISSUE #411: Support label-based sub-namespace resource management
i.e. revive and merge https://github.com/Shopify/kubernetes-deploy/pull/235

### PR DESCRIPTION
**Pull request by DazWorrall**
Closes #411 

This is little more than a rebase and refresh of #235 at the moment, from here we can figure out the next steps required to get this over the line. My only substantial change was a tweak to one test to fix a race where a pruned resource is still discoverable for a brief amount of time - is this ok?

https://github.com/Shopify/kubernetes-deploy/blob/13763f81bb742013c9cffa2b9f9143c112cf21f2/test/integration/kubernetes_deploy_test.rb#L138-L139

@KnVerey I saw you mention some potential work around secrets which might be a prerequisite for this, do you have any more context on that?

### CODE REVIEW

**Comment by KnVerey** [comment]
> I saw you mention some potential work around secrets which might be a prerequisite for this, do you have any more context on that?

This is the discussion that AFAIK was not addressed: https://github.com/Shopify/kubernetes-deploy/pull/235#discussion_r161610047

However, at this point, I think it would make more sense to do this first and rebase on it: https://github.com/Shopify/kubernetes-deploy/issues/209#issuecomment-463433301. Then we will get feature parity for secrets for free.

**Comment by benlangfeld** [comment]
@KnVerey To be clear, rebase this on a solution to #209, or the reverse?

**Comment by benlangfeld** [comment]
https://github.com/Shopify/kubernetes-deploy/pull/439 rebases this, addresses @dturn 's comment above and resolves the lint warnings.

**Comment by DazWorrall** [comment]
Superseded by #439

**Pull request closed without merging**
