### PR TITLE
[WIP] Watch script

### PR DESCRIPTION
**Pull request by KnVerey**
Same as https://github.com/Shopify/kubernetes-deploy/pull/382 but rebased on https://github.com/Shopify/kubernetes-deploy/pull/385

### CODE REVIEW

**Comment by hjanuschka** [comment]
is this PR dead? i would love to have a "watch" feature. i might jump in and give it a try.

**Comment by KnVerey** [comment]
Hey @hjanuschka, this PR is still on my radar, but is low priority. It was fully functional back in November, but the rebase I just did to make this PR a more useful reference was hairy, so I may have broken it. It also definitely needs work on tests.  

> i would love to have a "watch" feature

This was originally aiming to provide a debug script for our maintainers. In November I used it to debug performance problems in watching enormous namespaces. Are you saying you would like a watch command as part of the gem, i.e. `kubernetes-watch $NAMESPACE $CONTEXT [flags]`? I'm definitely open to that, but I would need to consult the other maintainers.

> i might jump in and give it a try.

That would be great! Please comment again if/when you get started so I know it's being taken care of. 😄

**Comment by hjanuschka** [comment]
currently i am having a tooling chain, that works quiet awesome.

but i am having a hard time, verifing that all deployements are finished. like pullinng images and stuff.


there is one group, suggesting HELM, i am against, because it introduces too much complexity.

and this project looks super awesome, however, i am having `PersistantVolumes` in my yaml's too. one problem i am suffering now is, that on intial deployment/fresh - the PV's aren't created - saw a PR that this is not going to happen.


so my current plan is, deploy/ship as we currently do (boiling down to one large yaml and `|kubectl apply -f ` - and afterwards - run `kubernetes-watch $NS $CTX`.


once the command finishes with exit code `0` - ship/Deploy is done, and CI can mark the pipeline as green, otherwise, RED.


i am giving it a try.

**Comment by hjanuschka** [comment]
as a sidenote, i tried it like this. (works, but i guess watch alone would be nicer)


```
generate giant YAML File > infra.yaml
cat infra.yml | kubectl apply -f -
cat infra.yml|kubernetes-deploy --template-dir=- $NS $CTX 
```

**Comment by KnVerey** [comment]
Closing in favour of https://github.com/Shopify/kubernetes-deploy/pull/481

**Pull request closed without merging**
